### ISSUE TITLE
IndexError in sort

### ISSUE THREAD

**Issue by Piyush-Srivastava** [agarwalsarthak121/web_crawlers#6]
sort is throwing a IndexError 
File "imdb.py", line 20, in <module>
    href = name[0].find('a')['href']
IndexError: list index out of range

**Comment by agarwalsarthak121** [comment]
Your movies names must be in proper format.
e.g. 'The Usual Suspects 1995 720p BluRay x264 AAC - Ozlem.mp4' is not in proper format
It should be like 'The Usual Suspects 1995.mp4' or 'The Usual Suspects.mp4'
It is giving this error because imdb came up with 0 results.
You can include a try catch statement to move on to next movie name so that the program doesn't stop abruptly.
Thanks
